apiVersion: v1
kind: Service
metadata:
  name: {{ include "smocker.fullname" . }}
  labels:
    {{- include "smocker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http-mock
      protocol: TCP
      name: http-mock
    - port: 8081
      targetPort: http-config
      protocol: TCP
      name: http-config
  selector:
    {{- include "smocker.selectorLabels" . | nindent 4 }}
