{{- $fullname := include "livebook.fullname" . }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $fullname) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname | quote }}
data:
  {{- if .Values.secrets.password }}
  password: {{ .Values.secrets.password | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data.password }}
  password: {{ $existingSecret.data.password | quote }}
  {{- else }}
  password: {{ (randAlphaNum 16) | b64enc | quote }}
  {{- end }}

  {{- if and $existingSecret $existingSecret.data.cookie }}
  cookie: {{ $existingSecret.data.cookie | quote }}
  {{- else }}
  cookie: {{ (randAlphaNum 64) | b64enc | quote }}
  {{- end }}

  {{- if and $existingSecret $existingSecret.data.key_base }}
  key_base: {{ $existingSecret.data.cookie | quote }}
  {{- else }}
  key_base: {{ (randAlphaNum 64) | b64enc | quote }}
  {{- end }}
