apiVersion: v1
kind: Service
metadata:
  name: {{ include "livebook.fullname" . }}
  labels:
    {{- include "livebook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "livebook.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "livebook.fullname" . }}-headless
  labels:
    {{- include "livebook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "livebook.selectorLabels" . | nindent 4 }}
